#!/usr/bin/env python3
"""Validate library/catalog.yaml and regenerate the human-readable library pages.

    python tools/catalog.py            # validate + write library/README.md and library/MAP.md
    python tools/catalog.py --check    # validate only (non-zero exit on problems)

catalog.yaml is the single source of truth for the library:

    categories:  {slug: {title, description}}
    papers:      [{id, title, short_name, authors, year, venue, arxiv, doi, category, tags, pdf,
                   one_liner, key_ideas, builds_on: [ids], cites: [ids], status, videos: [ids]}]
    paths:       [{id, title, why, steps: [{paper, note}]}]          # reading orders
    video_ideas: [{title, papers: [ids], story}]                     # multi-paper video plans
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
LIB = ROOT / "library"
CATALOG = LIB / "catalog.yaml"
STATUSES = {"unread", "skimmed", "reading", "read", "video"}


def load() -> dict:
    return yaml.safe_load(CATALOG.read_text(encoding="utf-8")) or {}


def validate(cat: dict) -> list[str]:
    errs: list[str] = []
    cats = cat.get("categories") or {}
    papers = cat.get("papers") or []
    ids = [p.get("id") for p in papers]
    seen = set()
    for i in ids:
        if i in seen:
            errs.append(f"duplicate paper id: {i}")
        seen.add(i)
    for p in papers:
        pid = p.get("id", "?")
        for key in ("id", "title", "year", "category") + (() if p.get("needs_pdf") else ("pdf",)):
            if not p.get(key):
                errs.append(f"{pid}: missing '{key}'")
        if p.get("category") and p["category"] not in cats:
            errs.append(f"{pid}: unknown category '{p['category']}' (add it under categories:)")
        if p.get("pdf") and not (ROOT / p["pdf"]).exists():
            errs.append(f"{pid}: pdf not found at {p['pdf']}")
        if p.get("pdf") and p.get("category") and not p["pdf"].startswith(f"library/{p['category']}/"):
            errs.append(f"{pid}: pdf should live under library/{p['category']}/")
        for rel in ("builds_on", "cites"):
            for ref in p.get(rel) or []:
                if ref not in seen:
                    errs.append(f"{pid}: {rel} refers to unknown id '{ref}'")
        if p.get("status", "unread") not in STATUSES:
            errs.append(f"{pid}: status must be one of {sorted(STATUSES)}")
        for v in p.get("videos") or []:
            if not (ROOT / "videos" / v / "video.yaml").exists():
                errs.append(f"{pid}: video '{v}' has no videos/{v}/video.yaml")
    for path in cat.get("paths") or []:
        for st in path.get("steps") or []:
            if st.get("paper") not in seen:
                errs.append(f"path {path.get('id')}: unknown paper '{st.get('paper')}'")
    for idea in cat.get("video_ideas") or []:
        for ref in idea.get("papers") or []:
            if ref not in seen:
                errs.append(f"video idea '{idea.get('title')}': unknown paper '{ref}'")
    listed = {(ROOT / p["pdf"]).resolve() for p in papers if p.get("pdf")}
    for pdf in LIB.rglob("*.pdf"):
        if pdf.resolve() not in listed:
            errs.append(f"untracked pdf (add it with tools/ingest.py): {pdf.relative_to(ROOT)}")
    return errs


def authors_short(p: dict) -> str:
    a = [x for x in (p.get("authors") or []) if x != "et al."]
    if not a:
        return ""
    last = lambda s: s.split()[-1]
    if len(a) == 1:
        return last(a[0])
    if len(a) == 2 and "et al." not in p.get("authors", []):
        return f"{last(a[0])} & {last(a[1])}"
    return f"{last(a[0])} et al."


def mermaid_id(pid: str) -> str:
    return "p_" + "".join(c if c.isalnum() else "_" for c in pid)


def render_readme(cat: dict) -> str:
    cats = cat.get("categories") or {}
    papers = cat.get("papers") or []
    by_cat = defaultdict(list)
    for p in papers:
        by_cat[p["category"]].append(p)
    out = ["# Library\n",
           "> Generated by `python tools/catalog.py` from `catalog.yaml` — edit the YAML, not this file.\n",
           f"{len(papers)} papers in {len(by_cat)} categories. "
           "See [MAP.md](MAP.md) for how they connect and suggested reading paths.\n"]
    badge = {"video": "🎬", "read": "✅", "reading": "📖", "skimmed": "👀", "unread": "·"}
    for slug in sorted(by_cat):
        info = cats.get(slug, {})
        out.append(f"\n## {info.get('title', slug)}  \n`{slug}`\n")
        if info.get("description"):
            out.append(f"{info['description']}\n")
        out.append("\n| | Paper | Year | Venue | In one line |\n|---|---|---|---|---|\n")
        for p in sorted(by_cat[slug], key=lambda p: (p.get("year", 0), p["id"])):
            name = p.get("short_name") or p["title"]
            link = (f"[{name}]({Path(p['pdf']).relative_to('library').as_posix()})" if p.get("pdf")
                    else f"{name} ⚠️ *PDF missing*")
            vids = " ".join(f"[🎬](../videos/{v}/)" for v in p.get("videos") or [])
            mark = vids or badge.get(p.get("status", "unread"), "·")
            out.append(f"| {mark} | {link} — "
                       f"{authors_short(p)} <br><sub>`{p['id']}`</sub> | {p.get('year', '')} | "
                       f"{p.get('venue', '')} | {(p.get('one_liner') or '').replace('|', '/')} |\n")
    out.append("\nLegend: 🎬 has an explainer video · ✅ read · 📖 reading · 👀 skimmed · · unread\n")
    todo = [p for p in papers if p.get("needs_pdf")]
    if todo:
        out.append("\n## PDFs to fetch\n\n")
        for p in todo:
            out.append(f"- **{p.get('short_name') or p['title']}** (`{p['id']}`): {p['needs_pdf']}\n")
    return "".join(out)


def render_map(cat: dict) -> str:
    cats = cat.get("categories") or {}
    papers = cat.get("papers") or []
    ids = {p["id"] for p in papers}
    out = ["# Map of the library\n",
           "> Generated by `python tools/catalog.py`. Arrows point from a paper to the papers that "
           "build on it.\n\n```mermaid\nflowchart LR\n"]
    by_cat = defaultdict(list)
    for p in papers:
        by_cat[p["category"]].append(p)
    for slug, ps in sorted(by_cat.items()):
        title = cats.get(slug, {}).get("title", slug)
        out.append(f'  subgraph {mermaid_id(slug)}["{title}"]\n')
        for p in sorted(ps, key=lambda p: p.get("year", 0)):
            label = (p.get("short_name") or p["id"]).replace('"', "'")
            out.append(f'    {mermaid_id(p["id"])}["{label}<br/>{p.get("year", "")}"]\n')
        out.append("  end\n")
    for p in papers:
        for ref in p.get("builds_on") or []:
            if ref in ids:
                out.append(f"  {mermaid_id(ref)} --> {mermaid_id(p['id'])}\n")
    out.append("```\n")
    name = {p["id"]: (p.get("short_name") or p["title"]) for p in papers}
    if cat.get("paths"):
        out.append("\n## Reading paths\n")
        for path in cat["paths"]:
            out.append(f"\n### {path['title']}\n{path.get('why', '')}\n\n")
            for i, st in enumerate(path.get("steps") or [], 1):
                out.append(f"{i}. **{name.get(st['paper'], st['paper'])}** — {st.get('note', '')}\n")
    if cat.get("video_ideas"):
        out.append("\n## Multi-paper video ideas\n")
        for idea in cat["video_ideas"]:
            ps = ", ".join(name.get(i, i) for i in idea.get("papers") or [])
            out.append(f"\n- **{idea['title']}** ({ps}) — {idea.get('story', '')}\n")
    return "".join(out)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="validate only")
    args = ap.parse_args(argv)
    cat = load()
    errs = validate(cat)
    for e in errs:
        print("✗", e)
    if args.check:
        print("catalog OK" if not errs else f"{len(errs)} problem(s)")
        return 1 if errs else 0
    (LIB / "README.md").write_text(render_readme(cat), encoding="utf-8")
    (LIB / "MAP.md").write_text(render_map(cat), encoding="utf-8")
    print(f"wrote library/README.md and library/MAP.md ({len(cat.get('papers') or [])} papers)"
          + (f" — {len(errs)} problem(s) above" if errs else ""))
    return 1 if errs else 0


if __name__ == "__main__":
    sys.exit(main())
